# Generated by Django 5.1.15 on 2026-06-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='kofi_handle',
            field=models.CharField(blank=True, help_text="Nome utente Ko-fi (es. 'angelosanzeri' per ko-fi.com/angelosanzeri). Compilato = mostra il bottone di supporto nel frontend; vuoto = nessun bottone.", max_length=80, verbose_name='Handle Ko-fi'),
        ),
    ]
