# Generated by Django 6.0.6 on 2026-06-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstraintTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('family', models.CharField(choices=[('base', 'Regole di base'), ('copertura', 'Copertura'), ('capacita', 'Capacità'), ('sequenza', 'Sequenza'), ('equita', 'Equità'), ('preferenze', 'Preferenze')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('param_schema', models.JSONField(default=list)),
                ('default_nature', models.CharField(choices=[('hard', 'Hard'), ('soft', 'Soft')], default='hard', max_length=4)),
                ('supports_soft', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['family', 'name'],
            },
        ),
    ]
