# Generated by Django 6.0.6 on 2026-06-09 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConstraintInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.JSONField(default=dict)),
                ('nature', models.CharField(choices=[('hard', 'Hard'), ('soft', 'Soft')], default='hard', max_length=4)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.constrainttemplate')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='scheduling.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('attrs', models.JSONField(blank=True, default=dict)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='scheduling.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'In coda'), ('RUNNING', 'In esecuzione'), ('OPTIMAL', 'Ottima'), ('FEASIBLE', 'Fattibile'), ('INFEASIBLE', 'Impossibile'), ('ERROR', 'Errore'), ('UNKNOWN', 'Tempo scaduto senza soluzione')], default='PENDING', max_length=12)),
                ('time_limit', models.PositiveIntegerField(default=30)),
                ('wall_time', models.FloatField(blank=True, null=True)),
                ('objective', models.FloatField(blank=True, null=True)),
                ('assignments', models.JSONField(blank=True, default=list)),
                ('violations', models.JSONField(blank=True, default=list)),
                ('conflicts', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='scheduling.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('code', models.CharField(help_text='es. M, P, N, Aula-3', max_length=20)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('start', models.TimeField(blank=True, null=True)),
                ('end', models.TimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='scheduling.dataset')),
            ],
            options={
                'ordering': ['day', 'start'],
            },
        ),
    ]
